#!/bin/bash
# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

FORCE=""
if [[ $1 == "-f" ]]; then
    FORCE=-f
    shift
fi

rmir_path=$1
output_path=$2

if [[ $(find $rmir_path -name "*.rmir" | wc -l) -ne 0 ]]; then
    riva-deploy $FORCE `find $rmir_path -name *.rmir -printf "%p:${MODEL_DEPLOY_KEY} "` $output_path;
fi
