#!/bin/bash
# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

set -euo pipefail

DOWNLOAD=""
DEPLOY=""
while getopts "dx" arg; do
    case $arg in
        d) DOWNLOAD="--force";;
        x) DEPLOY="-f" ;;
    esac
done
shift $((OPTIND-1))

RMIR_DIR=${RMIR_DIR:-/data/rmir}
MODEL_DIR=${MODEL_DIR:-/data/models}
download_ngc_models $DOWNLOAD $@
deploy_all_models $DEPLOY ${RMIR_DIR} ${MODEL_DIR}
