#!/bin/bash

# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

force_mode=false

ARTIFACT_DIR=${ARTIFACT_DIR:-/data/artifacts}
RMIR_DIR=${RMIR_DIR:-/data/rmir}

[ -d $ARTIFACT_DIR ] || mkdir $ARTIFACT_DIR
[ -d $RMIR_DIR ] || mkdir $RMIR_DIR

pushd $ARTIFACT_DIR


for model in "$@"
do
    if [[ "$model" == '--force' ]]; then
        force_mode=true
        continue
    fi
    model_loc=`echo $model | rev | cut -d "/" -f 1 | rev`
    model_name=`echo $model_loc | cut -d ":" -f 1`
    model_version=`echo $model_loc | cut -d ":" -f 2`

    # trying to retrieve version if user skipped it
    if [[ -z "${model_version}" || "${model_version}" == "${model_name}" ]]; then
        model_version="$(ngc registry model list --format_type csv --column version $model | awk -F ',' 'FNR>1 {print $NF}')"
    fi

    dir_name="${model_name}_v${model_version}"
    if [[ "$force_mode" == 'false' && -e ${dir_name} ]]; then
        echo "Directory ${dir_name} already exists, skipping. Use '--force' option to override."
        continue
    elif [[ "$force_mode" == 'true' && -e ${dir_name} ]]; then
        rm -Rf ${dir_name}
    fi

    attempts=3
    echo "  > Downloading $model..."
    for ((i = 1 ; i <= $attempts ; i++)); do
        ngc registry model download-version $model
        if [ $? -ne 0 ]; then
            echo "  > Attempt $i out of $attempts failed"
            if [ $i -eq $attempts ]; then
                echo "Error occurred downloading '$model'. Exiting."
                exit 1
            else
                echo "  > Trying again..."
                if [[ -e ${dir_name} ]]; then
                    echo " > Cleaning up partial download  ${dir_name}"
                    rm -Rf ${dir_name}
                fi
                continue
            fi
        else
            break
        fi
    done

    cp ${model_name}_v${model_version}/*.rmir $RMIR_DIR
done

popd
